name: Smoke tests on DUTs

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build train"]
    types:
      - completed
jobs:

  Smoke:
    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/smoke-tests.yml@master
    secrets:
      KEY_CI: ${{ secrets.KEY_CI }}
